# Generated by Django 5.0.6 on 2024-08-15 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_page_imagelayer_textlayer_videolayer'),
    ]

    operations = [
        migrations.AddField(
            model_name='textlayer',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
