# Generated by Django 5.0.6 on 2024-08-16 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_textlayer_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagelayer',
            name='order',
            field=models.IntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='textlayer',
            name='order',
            field=models.IntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='videolayer',
            name='order',
            field=models.IntegerField(editable=False),
        ),
    ]
