# Generated by Django 5.0.6 on 2024-08-19 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_imagelayer_order_alter_textlayer_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagelayer',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imagelayer',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
