# Generated by Django 5.0.6 on 2024-08-19 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_imagelayer_text_imagelayer_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagelayer',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
