# Generated by Django 5.0.6 on 2024-08-20 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_imagelayer_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagelayer',
            options={},
        ),
        migrations.RemoveField(
            model_name='imagelayer',
            name='link',
        ),
        migrations.RemoveField(
            model_name='imagelayer',
            name='order',
        ),
        migrations.CreateModel(
            name='ImageLayerLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('image_layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='portfolio.imagelayer')),
            ],
        ),
    ]
