# Generated by Django 5.0.6 on 2024-08-20 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_alter_imagelayer_options_remove_imagelayer_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagelayerlink',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
