# Generated by Django 5.0.6 on 2024-08-20 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_imagelayerlink_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagelayer',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='imagelayer',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
